name: Update Gaphor version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true
  repository_dispatch:
    types: [version-update]

env:
  python_version: '3.12'

permissions:
  contents: write 
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ env.python_version }}
      - name: Install Linux dependencies
        run: sudo apt-get update -qq && sudo apt-get install -qq --no-install-recommends libgirepository1.0-dev
      - name: Update version
        run: |
          if test -z "${{ github.event.inputs.version }}${{ github.event.client_payload.version }}"; then echo "No version provided"; exit 1; fi
          make only-update VERSION=${{ github.event.inputs.version }}${{ github.event.client_payload.version }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          commit-message: update to version ${{ github.event.inputs.version }}${{ github.event.client_payload.version }}
          title: Update to version ${{ github.event.inputs.version }}${{ github.event.client_payload.version }}
          body: Update to latest release
          branch: release-${{ github.event.inputs.version }}${{ github.event.client_payload.version }}
          base: master
